version: '3.6'
volumes:
  mysql_data:

services:
  node:
    build: ./infra/node
    volumes:
    - ./www:/home/node/www:cached

  mysql:
    platform: linux/x86_64
    build: ./infra/mysql
    volumes:
    - mysql_data:/var/lib/mysql:cached
    - ./dump:/dump
    ports:
    - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: pass

  php:
    build: ./infra/php
    volumes:
    - ./www:/var/www/html:cached

  front:
    build: ./infra/nginx
    ports:
    - 80:80
    volumes:
    - ./www:/var/www/html:cached
